# Generated by Django 5.2.3 on 2025-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_fav_ad_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.TextField(blank=True, help_text='Enter tags separated by commas'),
        ),
    ]
