# Generated by Django 5.2.7 on 2025-07-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_owner'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE ads_ad_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                title VARCHAR(200) NOT NULL,
                price DECIMAL(7,2) NULL,
                text TEXT NOT NULL,
                owner_id INTEGER NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL
            );
            INSERT INTO ads_ad_new SELECT * FROM ads_ad;
            DROP TABLE ads_ad;
            ALTER TABLE ads_ad_new RENAME TO ads_ad;
            """,
            reverse_sql=""
        ),
    ]
